### ISSUE TITLE
gcc:10.2.0 build fails "explicit template specialization cannot have a storage class"

### ISSUE THREAD

**Issue by bartoszek** [vukics/cppqed#9]
Build fine with `clang:11.0.1` but against `gcc:10.2.0` build fails complaining about `template specialization` in `Random.h`
`build_env:{os:Linux,distro:Arch,gcc:10.2.0,clang:11.0.1,boost:1.75.0,python:3.9.1,eigen:3.3.9,gsl:2.6:cmake:3.19.3,ninja:1.10.0}`
#### `relevent lines:`
https://github.com/vukics/cppqed/blob/34290aee8628f2a78b5a72797a4678952db4c580/CPPQEDutils/Random.h#L104-L113
#### `gcc error:`
```
FAILED: CPPQEDutils/CMakeFiles/CPPQEDutils.dir/Random.cc.o
/usr/lib/colorgcc/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_SERIALIZATION_DYN_LINK -DBZ_HAVE_BOOST_SERIALIZATION -DCPPQED_HAS_GSL -DCPPQEDutils_EXPORTS -DDO_NOT_USE_FLENS -DEIGEN3_FOUND -ICPPQEDutils -I/home/bartus/AUR/cppqed-git/src/cppqed-git/CPPQEDutils -I/home/bartus/AUR/cppqed-git/src/cppqed-git/CPPQEDutils/thirdPartyRandom/Xoshiro-cpp -I/home/bartus/AUR/cppqed-git/src/cppqed-git/CPPQEDutils/thirdPartyRandom/pcg-cpp/include -ICPPQEDutils/thirdPartyRandom -I/home/bartus/AUR/cppqed-git/src/cppqed-git/CPPQEDutils/thirdPartyRandom -Iblitz -Iblitz/blitz/.. -Iblitz/blitz -I/home/bartus/AUR/cppqed-git/src/cppqed-git/blitz/blitz -I/home/bartus/AUR/cppqed-git/src/cppqed-git/blitz/blitz/array/../.. -Iblitz/blitz/array -I/home/bartus/AUR/cppqed-git/src/cppqed-git/blitz/blitz/array -Iblitz/blitz/meta -I/home/bartus/AUR/cppqed-git/src/cppqed-git/blitz/blitz/meta -isystem /home/bartus/AUR/cppqed-git/src/cppqed-git/blitz -isystem /usr/include/eigen3 -D_FORTIFY_SOURCE=2 -march=native -mtune=native -O2 -pipe -fstack-protector-strong -fno-plt -DBOOST_BIND_GLOBAL_PLACEHOLDERS -std=c++17 -O3 -DNDEBUG -fPIC -Wall -Wextra -Wpedantic -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -Wno-ignored-qualifiers -Wno-sign-compare -Wno-overloaded-virtual -Wunreachable-code -std=c++17 -MD -MT CPPQEDutils/CMakeFiles/CPPQEDutils.dir/Random.cc.o -MF CPPQEDutils/CMakeFiles/CPPQEDutils.dir/Random.cc.o.d -o CPPQEDutils/CMakeFiles/CPPQEDutils.dir/Random.cc.o -c /home/bartus/AUR/cppqed-git/src/cppqed-git/CPPQEDutils/Random.cc
In file included from /home/bartus/AUR/cppqed-git/src/cppqed-git/CPPQEDutils/Random.cc:3:
/home/bartus/AUR/cppqed-git/src/cppqed-git/CPPQEDutils/Random.h:104:1: error: explicit template specialization cannot have a storage class
  104 | static const std::string EngineID_v<GSL_Engine> = "GSL_Taus2";
      | ^~~~~~
/home/bartus/AUR/cppqed-git/src/cppqed-git/CPPQEDutils/Random.h:107:1: error: explicit template specialization cannot have a storage class
  107 | static const std::string EngineID_v<std::mt19937_64> = "STD_MT19937_64";
      | ^~~~~~
/home/bartus/AUR/cppqed-git/src/cppqed-git/CPPQEDutils/Random.h:110:1: error: explicit template specialization cannot have a storage class
  110 | static const std::string EngineID_v<pcg64> = "PCG64";
      | ^~~~~~
/home/bartus/AUR/cppqed-git/src/cppqed-git/CPPQEDutils/Random.h:113:1: error: explicit template specialization cannot have a storage class
  113 | static const std::string EngineID_v<XoshiroCpp::Xoshiro256PlusPlus> = "Xoshiro256pp";
      | ^~~~~~`
```

**Comment by vukics** [comment]
I had a lot of trouble with these specializations. It seems that if they are not declared static, then gcc doesn’t complain, either.

**Comment by vukics** [comment]
OK, without `static` it doesn’t compile with clang :)
Solution: replace `static` with `inline`. That way both compilers accept the code.

**Comment by vukics** [comment]
Some tests still don’t compile with gcc 10.2.0

**Comment by bartoszek** [comment]
Confirmed, build fine but fails in some test.
